name:                haskell-jp-blog-artifact
version:             0.1.0.0
github:              "fumieval/haskell-jp-blog-artifact"
license:             BSD3
author:              "Fumiaki Kinoshita"
maintainer:          "fumiexcel@gmail.com"
copyright:           "Copyright (c) 2017 Fumiaki Kinoshita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fumieval/haskell-jp-blog-artifact#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- bytestring
- http-client
- text
- http-types
- http-client-tls
- text
- aeson
- transformers
executables:
  haskell-jp-blog-artifact-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded -Wall
